window.PinheadRulePacks=(function(){
var classicRules={
'abra ca dabra':[
['Collect number 1','Collect the 1 lane.','Watch the four numbered top lanes and aim for 1 if it is still missing.'],
['Collect number 2','Collect the 2 lane.','Use a controlled plunge or upper-playfield rebound to pass through lane 2.'],
['Collect number 3','Collect the 3 lane.','Check the number inserts first; collect 3 only if it has not registered this ball.'],
['Collect number 4','Collect the 4 lane.','A soft plunge can help reach 4; adjust the plunger strength to your machine.'],
['Complete 1–4','Collect all four numbered lanes in one ball.','Track each lane and prioritize whichever number remains unlit.'],
['Clear the ten-drop bank','Knock down all ten drop targets.','Target hits are worth more as the displayed bonus rises; finish the full bank.'],
['Reset the drop targets','Clear the ten-drop bank, then hit the center stand-up target.','The center target resets the bank after it is cleared, allowing another cycle.'],
['Hit a 5K target','Raise target value to 5K, then hit a drop target.','Collect numbered lanes to increase the displayed bonus before shooting the drops.'],
['Complete numbers and targets','Complete 1–4 and clear all ten drops in one ball.','Finish the missing lane first if possible, then clear the bank while maintaining control.'],
['Repeat the target cycle','Clear the ten-drop bank, reset it with the center target, and clear it again.','After the first bank is down, aim for the center reset target and repeat the target sequence.']],
'atlantis':[
['Hit a left drop-target pair','Knock down a pair of left-side drops with one shot.','The left drops are valuable in pairs; try a controlled cross-playfield shot from the right flipper.'],
['Collect the lit yellow lane','Roll through the currently lit yellow lane.','Top slingshot hits change the lit lane, so confirm the lamp before plunging or shooting.'],
['Advance the 1–9 sequence','Collect the next number in the 1–9 sequence.','Follow the number inserts; only the currently lit next number advances the sequence.'],
['Complete 1–9','Collect numbers 1 through 9.','Track the lit number and work through the sequence rather than chasing random lanes.'],
['Clear the left drop bank','Knock down every left-side drop target.','Use bank shots or a controlled shot from the right flipper; confirm the full bank is down.'],
['Clear the right drop bank','Knock down every right-side drop target.','Work the right bank when the return is favorable; fast balls on the right flipper can drain.'],
['Hit three enhanced targets','Score three hits while target-value lamps are lit.','Target pairs increase value; watch for the higher-value lamps before shooting.'],
['Collect a waterfall number','Send the ball through a lit number lane in the right waterfall.','The waterfall is risky near the lower-right exit; take the shot when the ball is controlled.'],
['Complete a number and a pair','Advance the next number and clear a left drop-target pair.','Do the lane when it is safely available, then return to the left drops.'],
['Complete sequence and bank','Complete the 1–9 sequence and clear one full drop bank.','This combines both main features; verify the final number and the cleared bank before game over.']],
'big brave':[
['Complete the three star rollovers','Roll through all three top star lanes.','Send the ball up top and track the three star inserts.'],
['Light double bonus','Complete all three top lanes to light double bonus.','Finish the remaining top lane and confirm the double-bonus lamp.'],
['Hit the vari-target','Shoot the vari-target and register its award.','Use a controlled shot; a miss can rebound toward the drain.'],
['Max the vari-target','Drive the vari-target to its maximum award.','A stronger accurate shot pushes the target farther; confirm the top award registers.'],
['Double bonus plus vari-target','Light double bonus, then hit the vari-target in the same ball.','Finish the three top lanes first, then take the vari-target when the shot is controlled.'],
['Clear the upper-left drops','Knock down the upper-left drop-target group.','Aim for the target faces and watch for dangerous center rebounds.'],
['Earn five bonus advances','Advance the end-of-ball bonus five times.','Work the upper playfield and top lanes, then check the bonus count.'],
['Collect a lit lane','Roll through a lane lit for an enhanced award.','Check the lane lamps before aiming up top.'],
['Complete the star lanes twice','Complete all three top star lanes two times in one game.','After the first completion, track the reset state and collect all three again.'],
['Max base bonus and double it','Reach maximum base bonus and activate double bonus.','Build bonus through upper-playfield activity, then finish the top lanes.']],
'centigrade 37':[
['Complete A–B–C–D','Register all four top letters.','Check the A, B, C and D inserts and finish whichever letters remain.'],
['Light the drop targets for 5K','Complete A–B–C–D to light the drop targets for 5K.','Finish the four-letter sequence and confirm the 5K target lamps.'],
['Clear the lit drop bank','Knock down the drop targets while their 5K feature is lit.','Complete A–D first, then shoot the bank while its higher value is active.'],
['Score the top saucer','Capture the ball in the top saucer.','The top saucer is a key shot from the left flipper; confirm the ball is captured.'],
['Collect a 5K return lane','Roll through a return lane lit for 5,000.','Track the lit lane and take it when the ball feeds safely.'],
['Letters plus saucer','Complete A–D and score the top saucer in the same ball.','Finish the letters, then shoot the saucer from a controlled flipper.'],
['Hit a lit bullseye','Hit a bullseye after its feature is lit.','Clear the required drops and check the bullseye insert before shooting.'],
['Complete A–D twice','Finish the four-letter sequence two times.','After the first set, follow the reset lamps and complete all four letters again.'],
['Clear two drop banks','Clear two distinct drop-target banks in one game.','Use the letter feature to raise target value, then clear each full bank.'],
['Max bonus and collect saucer','Build bonus to its maximum and collect it through the saucer.','Advance bonus on the upper playfield and use the saucer to collect the accumulated award.']],
'dimension':[
['Clear a color bank','Knock down all five drop targets of one color.','A completed color set lights its matching saucer and lane; track the five targets in that bank.'],
['Collect a matching saucer','Complete a color bank, then collect that color’s saucer.','Clear all five same-color drops, then shoot the newly lit top saucer.'],
['Collect a matching lane','Complete a color bank and roll through its matching lane.','After clearing the color bank, use upper-playfield flow to collect its lane award.'],
['Complete the green bank','Clear the five green drop targets.','Green is one of the upper colors; its completed set lights a return lane and saucer.'],
['Complete the red bank','Clear the five red drop targets.','Track the red bank and confirm all five targets are down.'],
['Complete the yellow bank','Clear the five yellow drop targets.','Finish the full yellow bank and check its matching lamps.'],
['Complete the blue bank','Clear the five blue drop targets.','Finish the full blue bank and check its matching lamps.'],
['Advance bonus multiplier','Complete the top three lanes to advance multiplier.','Watch the top lane inserts and finish the set to advance the bonus multiplier.'],
['Reach 5× multiplier','Advance the bonus multiplier to 5×.','Repeat the top-lane feature until 5× is lit.'],
['Collect two color saucers','Complete two color banks and collect both matching saucers.','Work one color set at a time and collect each corresponding saucer award.']],
'drop-a-card':[
['Collect the lit top lane','Roll through the currently lit top lane.','One top lane is lit for the skill shot; use the appropriate plunge strength.'],
['Clear the left drop bank','Knock down all left-side drop targets.','Clearing a side set lights its matching bumpers and lanes for higher values.'],
['Clear the right drop bank','Knock down all right-side drop targets.','Finish the right bank and confirm its feature lamps change.'],
['Light the left-side feature','Complete the left drop set to light its bumpers and lanes.','Track the left target bank and look for the matching lane and bumper lamps.'],
['Light the right-side feature','Complete the right drop set to light its bumpers and lanes.','Track the right target bank and look for the matching lane and bumper lamps.'],
['Collect a 500-point top lane','Roll through one of the upper 500-point lanes.','After clearing targets, send the ball up top and guide it into a 500 lane.'],
['Complete both side banks','Clear the left and right drop-target sets.','Target progress is retained; finish one bank and then the other.'],
['Hit both lower stand-ups','Hit the lower-left and lower-right stand-up targets.','These targets matter once the drops are cleared; take care with target rebounds.'],
['Score five bumper hits after drops','Clear the target sets, then score five bumper hits.','Once the drops are down, send the ball up top and count registered bumper hits.'],
['Complete lane and both banks','Collect a lit top lane and clear both side target banks.','Take the lit lane when available, then complete the two banks.']],
'jacks open':[
['Collect one suit lane','Complete one of the four top suit lanes.','Uncollected suit lanes are lit; choose a lane you still need.'],
['Collect three suit lanes','Complete three of the four top suit lanes.','Drop-target value rises with the first three completed lanes, so track lane progress.'],
['Complete all four suit lanes','Collect all four top suit lanes.','Completing the fourth resets the lanes and lowers drop value; verify the reset.'],
['Complete two Jacks','Knock down both Jack targets.','The first poker hand is two Jacks; clear both J targets.'],
['Complete three Queens','Knock down all three Queen targets.','After the Jacks, clear the three Queen targets to advance the hand.'],
['Complete a full house','Complete three Queens and two Kings.','Finish the Queen group and both King targets; confirm the hand advances.'],
['Complete the Royal Flush','Clear all five Royal Flush heart targets.','Follow the poker-hand progression and finish all five heart targets.'],
['Complete a hand award','Finish one poker-hand stage.','Follow the target sequence: Jacks, Queens, full house, then Royal Flush.'],
['Raise target value first','Complete three suit lanes, then hit a drop target.','Build lane progress before shooting drops; completing the fourth lane resets the lane set.'],
['Complete two hand stages','Finish two successive poker-hand stages in one game.','After a hand completes, follow the newly required target group.']],
'jet spin':[
['Hit the roto target','Make a successful shot to the central roto target.','The roto target is the main repeatable feature; aim from the right flipper.'],
['Hit the left bullseye','Hit the narrow left bullseye target.','Use a controlled shot from the right flipper and watch the rebound.'],
['Score the right saucer','Capture the ball in the right-side saucer.','Take the saucer shot when the ball is controlled and verify it captures.'],
['Earn five bonus advances','Score five bonus advances in one ball.','The roto target can award multiple advances; track the bonus count.'],
['Max the 15K bonus','Reach the 15K base-bonus maximum.','Use the roto target and upper features to advance bonus; confirm the counter reaches 15K.'],
['Hit the roto target three times','Make three roto-target shots in one game.','Favor the repeatable roto target and count successful registered hits.'],
['Collect a lit top lane','Roll through a currently lit top lane.','Check the lane lamps before plunging or shooting up top.'],
['Hit roto and bullseye','Score both the roto target and left bullseye in one game.','Prioritize the safer roto shot and attempt the narrow bullseye from a controlled right-flipper position.'],
['Target then saucer','Hit a target, then collect the saucer award in the same ball.','Recover the target rebound and take the saucer if the return path is safe.'],
['Hit the roto target five times','Make five successful roto-target shots in one game.','Stay with the main roto target and count only confirmed hits.']]
  };
  
var classicRules2={
'jungle queen':[
['Clear one side drop bank','Knock down all five drops on one side.','Use the upper mini-flippers to direct the ball to the side drops, then finish the remaining targets.'],
['Light a 5K side lane','Clear a side’s five drops to light its 5K lane.','Complete all five targets on the same side and confirm the matching lane lights.'],
['Collect a lit side lane','Roll through a side lane after it lights for 5K.','After a bank is cleared, aim for its corresponding lane when the ball feeds safely.'],
['Score an upper saucer','Capture the ball in either upper saucer.','A cleared side bank makes its upper saucer a valuable target; confirm capture.'],
['Complete A-B-C','Collect the A, B and C lanes.','Track the three letters; the full set doubles bonus.'],
['Activate double bonus','Complete A-B-C to light double bonus.','Finish the last missing letter and verify the double-bonus feature is active.'],
['Clear both side banks','Clear both five-target banks in one game.','Complete one side, then the other; each side lights its own 5K lane.'],
['Collect both 5K lanes','Light and collect both side lanes.','Clear both banks first, then collect each lit lane award.'],
['A-B-C plus a target bank','Light double bonus and clear a side bank in one ball.','Complete the three letters and all five drops on one side before draining.'],
['Collect both upper saucers','Capture the left and right upper saucers in one game.','Use the saucers above the cleared target banks and confirm both awards.']],
'lawman':[
['Open the waterfall gate','Hit the stand-up target right of the waterfall lanes.','The gate-opening target sits to the right of the waterfall; confirm the gate opens before attempting the waterfall.'],
['Shoot the waterfall with gate open','Send the ball through the right waterfall while the gate is open.','Open the gate first, then shoot the upper-right waterfall and watch the lower-right exit.'],
['Clear the left drop bank','Knock down the complete left drop-target bank.','A full bank completion is worth more than scattered target hits; verify every drop is down.'],
['Collect a lit waterfall lane','Roll through a currently lit waterfall lane.','Top and waterfall bonus lanes are synchronized; check which lane is lit before shooting.'],
['Repeat the waterfall pass','Make two waterfall passes with the gate open.','The gate can close after switch hits, so check its state before the second attempt.'],
['Advance bonus to 1,000','Advance the bonus reel to the 1,000 value.','Scoring points advances bonus; track the reel and preserve the bonus by avoiding a tilt.'],
['Clear both side target banks','Complete the left and right drop-target banks.','Finish one bank fully before moving to the other; the completion award registers when the bank clears.'],
['Collect a lane and clear a bank','Collect one lit waterfall lane and complete one drop bank.','Take the lane when safely available, then clear a full bank.'],
['Collect final-ball double bonus','Reach the final ball and collect double bonus.','Build bonus through targets and lanes, then avoid tilting during the final-ball bonus count.'],
['Open gate, waterfall, and return','Open the gate, make a waterfall pass, and return to the main playfield.','The open gate is what makes the waterfall exit survivable; confirm the ball returns to the main playfield.']],
'black hole':[
['Open the re-entry gate','Complete the four lower-right stand-up targets and open the gate.','Clear all four targets, then get the ball through the lane beneath them; verify the gate is open before visiting the lower playfield.'],
['Clear the main target bank','Complete the main-level target bank.','Finishing this bank also lights the main-level captive-ball hole and helps qualify a lock.'],
['Lock a lower-playfield ball','Lock a ball in the lower-left lock.','Send the ball to the lower level and shoot the lower-left lock; this lock can retain a ball between player turns.'],
['Lock an upper ball','Lock a ball at the main-level lock above the upper-left flipper.','Qualify the lock through the target bank or lower-playfield feature, then shoot the lit lock.'],
['Start lower-level multiball','Lock two balls and send a third ball to the lower playfield.','Once both locks are occupied, plunge the third ball to release the lower lock and start lower-level multiball.'],
['Return from the lower playfield','Open the gate and successfully return a ball from below.','The lower-playfield exit returns safely only while the re-entry gate is open.'],
['Light 2× lower-playfield scoring','Complete one upper drop-target bank.','One upper bank lights 2× on the lower playfield; verify the multiplier when you get downstairs.'],
['Light 3× lower-playfield scoring','Complete both upper drop-target banks.','Finish both banks to light 3× lower-playfield scoring.'],
['Advance lower-playfield bonus multiplier','Complete the top three lanes or the lower-right rollunder.','The lower-level rollunder and upper top lanes advance the bonus multiplier; use whichever shot is available.'],
['Complete the lock sequence','Lock two balls and start multiball via the lower playfield.','Qualify and secure both locks, then send the third ball to the lower level to trigger multiball.']],
'centaur':[
['Spell O-R-B-S in order','Complete the O-R-B-S drop targets in order.','Hit O, then R, then B, then S; an out-of-order hit resets the required sequence.'],
['Start Centaur multiball','Complete ORBS and shoot a release target.','ORBS builds virtual locks; hit the upper-right release target or the target behind the captive-ball drops to release locked balls.'],
['Complete 1-2-3-4 in order','Hit the numbered targets in sequence.','Follow 1, 2, 3, 4 in order to increase bonus advances and enable collect-bonus/release features.'],
['Collect bonus at the upper-right target','Light and hit the upper-right collect-bonus target.','Complete 1-2-3-4 in order, then shoot the lit upper-right target while the bonus award is ready.'],
['Reach 5× bonus multiplier','Complete the top three lanes until 5× is lit.','Use lane change to select missing top lanes; the multiplier advances through repeated lane sets.'],
['Hit the captive ball','Make a successful captive-ball shot.','Aim at the left captive ball; crossing the two left-arc star rollovers first doubles the shot value.'],
['Complete all four bottom lanes','Collect all four return/outlanes with lane change.','The flipper buttons change the left and right lane lamps independently; track the four lit inserts.'],
['Trigger multiball with the fourth lane','Complete three bottom lanes and drain through the fourth while a ball is locked.','With one ball locked, the fourth lane can trigger multiball if the other three lanes are already complete.'],
['Collect a 5× bonus award','Time the collect-bonus shot for its 5× multiplier.','Watch the lane leading to the collect target and shoot when the timed multiplier reaches 5×.'],
['Start multiball and hit captive ball','Start multiball, then hit the captive ball.','Complete ORBS/release to start multiball, then use a controlled shot on the captive ball.']],
'firepower':[
['Light the spinner','Complete the required numbered target sets to light the spinner.','Hit the center numbered stand-ups; settings may require one or both sets, so use the spinner insert as confirmation.'],
['Light the kickback','Complete the targets that qualify the left kickback.','Depending on the game settings, numbered targets or blue POWER targets may control the kickback; watch its lamp.'],
['Lock a ball','Qualify and shoot the lit lock saucer.','Complete the target set required by the machine, then shoot the lit lock saucer near the upper-left flipper.'],
['Start multiball','Lock the required balls and start multiball.','Follow the lock lamps and make the displayed start/release shot when the required balls are locked.'],
['Complete F-I-R-E','Collect all four top F-I-R-E lanes.','Track the four top lane inserts; lane change can help select missing letters.'],
['Complete the blue POWER targets','Hit all three blue POWER stand-up targets.','Shoot each of the three blue targets; completing the set lights return lanes and advances bonus.'],
['Reach 5× bonus multiplier','Complete top lane sets until 5× bonus is lit.','Each complete F-I-R-E lane set advances the multiplier up to 5×.'],
['Increase the center-target award','Complete FIRE and POWER sets, then hit the center target.','The center target between the I and R lanes increases in value as both feature sets are completed.'],
['Collect a lit spinner award','After lighting the spinner, shoot through it.','Use the right flipper for the spinner when lit and confirm the higher-value state.'],
['Light kickback and spinner','Complete the target features that light both kickback and spinner.','Track numbered and POWER targets; settings vary, so confirm both inserts are lit rather than assuming.']],
'flash gordon':[
['Reach 2× multiplier','Hit the second right-side inline target to light 2×.','Work the right inline drops and verify the 2× bonus lamp.'],
['Reach 3× multiplier','Hit the third right-side inline target to light 3×.','Complete the right inline progression and check the multiplier insert.'],
['Reach 4× multiplier','Clear the upper-playfield drop bank.','Finish the upper target bank; the 4× multiplier lamp confirms the step.'],
['Reach 5× multiplier','Clear the lower-left target bank.','After 2×, 3× and 4×, clear the lower-left bank and confirm 5×.'],
['Light the left spinner','Complete the lower-left target bank once.','The first completion lights the left spinner; shoot it while lit.'],
['Light the right spinner','Complete the lower-left target bank a second time.','Repeat the bank and check the right spinner insert.'],
['Activate a playfield multiplier','Qualify 2× or 3× playfield scoring and shoot the center saucer.','Complete the upper flashing targets for 2× or lower targets for 3×, then capture the center saucer.'],
['Collect the flashing upper-bank bonus','Complete the upper target bank while it is flashing.','Watch for the flashing bonus state and clear the whole bank before the targets reset.'],
['Collect bonus from the upper playfield','Knock down the single target above the upper flipper to route to the plunger lane.','The upper target enables a bonus-collect route; follow the ball back to the plunger lane and confirm collection.'],
['Qualify both playfield multipliers','Complete the upper and lower flashing target features.','Finish the upper feature for 2× and the lower feature for 3×; the center saucer activates the multiplier.']],
'quicksilver':[
['Clear the right three-bank','Knock down all three right-side drop targets.','The bank is a priority: one sweeping shot can clear several targets and feed the spinner.'],
['Reach 5× bonus multiplier','Complete the right three-bank progression until 5× is lit.','Keep working the right bank and watch the multiplier inserts for 5×.'],
['Collect a lit spinner','Light the opposite spinner with a return lane and shoot it before it times out.','Spinner lights are temporary; use a flow shot as the ball returns rather than waiting for a cradle.'],
['Clear the center four-bank','Knock down all four center drop targets.','Completing the center bank raises the left saucer value and spots a letter.'],
['Collect the left saucer award','Raise the saucer value with the center bank, then capture the saucer.','Confirm the value has increased, then shoot the saucer and verify the award.'],
['Advance base bonus','Use top lanes and lettered stand-up targets to advance bonus.','Watch the bonus count after each top-lane or lettered-target hit.'],
['Light both opposite spinners','Use both return lanes to light their opposite spinners.','Each return lane lights the opposite spinner only briefly; collect both before the lamps expire.'],
['Score three lit spinner turns','Score at least three spinner turns while lit.','Take the lit spinner immediately and verify the higher-value feature is active.'],
['Reach 75K base bonus','Build base bonus to its 75K maximum.','Use top lanes and lettered stand-ups; confirm the base bonus counter reaches 75K.'],
['Reach 5× and collect spinner','Reach 5× bonus and collect a lit spinner shot.','Complete the multiplier progression, then use a return lane to light and collect the spinner.']],
'seawitch':[
['Complete the center target bank','Clear the center drop bank to start multiplier progression.','Finish the center bank; this is the first step in the target-bank sequence.'],
['Reach 3× multiplier','Complete the left target bank after the center bank.','Follow the bank order: center advances to 2×, left to 3×.'],
['Reach 4× multiplier','Complete the top target bank after the earlier banks.','Finish the top bank in sequence and verify 4× is lit.'],
['Reach 7× multiplier','Repeat the target-bank sequence until 7× is lit.','Continue center, left, top bank progression and check the multiplier lamps.'],
['Increase spinner value','Hit all four upper star stand-up targets.','Each upper star increases spinner value; complete all four for the highest value.'],
['Collect a lit spinner','Shoot through the spinner after lighting its higher value.','Check the spinner insert and take the shot while the award is active.'],
['Complete all three banks','Clear center, left and top banks in one ball.','Finish each full bank; all three completed on the same ball light double value on loops.'],
['Collect a doubled loop','Complete all three banks, then score a loop shot.','After the banks light the doubler, shoot through the top star rollover to collect the doubled loop value.'],
['Reach 39K base bonus','Build base bonus to its 39K maximum.','Use targets and lanes to advance bonus and check the count before end-of-ball.'],
['Score two lit loop awards','Collect two loop awards while loop value is active.','Complete target banks to raise loop value, then shoot through the top star rollover.']],
'sorcerer':[
['Lock a ball at the left ramp','Make the left ramp shot to lock a ball.','The left ramp is the main lock shot; two successful lock-ramp shots normally qualify multiball.'],
['Start Sorcerer multiball','Complete the lock-ramp sequence and start multiball.','Lock the required balls with the left ramp and confirm multiball starts.'],
['Reach 5× playfield multiplier','Shoot the lock ramp during multiball until 5× is lit.','The multiplier advances 2×, 3×, then 5×; make the lit lock-ramp shot each time.'],
['Spell S-O-R-C-E-R-O-R','Complete all letters in SORCEROR.','Work the letter features when safe; finishing the word lights the spinners.'],
['Collect a lit spinner during multiball','During multiball, shoot a lit spinner.','Complete SORCEROR to light the spinners, then collect one during multiball.'],
['Complete A-B-C-D lanes','Roll through all four top lanes.','Track the top lane inserts; the completed set advances the bonus multiplier.'],
['Reach 8× bonus multiplier','Complete top-lane sets until 8× is lit.','The A-B-C-D lanes advance bonus through 2×, 4×, 6× and 8×.'],
['Clear the upper-right three-bank','Clear all three upper-right drops before they reset.','The bank is timed; finish it before the targets reset to collect the award.'],
['Collect hold bonus','Clear the upper-right bank while hold bonus is lit.','Check the hold-bonus indicator, then finish the timed three-bank.'],
['Start multiball and reach 5×','Start multiball and advance playfield multiplier to 5×.','Lock balls with the left ramp, then repeat the lit ramp shot during multiball.']],
'star gazer':[
['Collect one zodiac symbol','Hit a lit zodiac drop target.','The twelve drop targets represent zodiac symbols; shoot one that is still lit.'],
['Complete all twelve zodiac symbols','Collect all twelve zodiac symbols.','Work the lit zodiac targets and rollover letters until all twelve register.'],
['Light 12K Super Bonus','Complete the first full zodiac set.','Collect all twelve symbols and verify the 12K Super Bonus lamp.'],
['Light 24K Super Bonus','Complete a second zodiac set.','After the first set, continue collecting symbols until 24K Super Bonus lights.'],
['Light 36K Super Bonus','Complete a third zodiac set.','Continue the zodiac collection until the 36K Super Bonus lamp lights.'],
['Advance bonus multiplier','Complete one of the lower two drop banks.','The lower banks advance the multiplier; clear a bank and check the multiplier lamps.'],
['Reach 10× multiplier','Complete the lower-bank progression to reach 10×.','Follow the 1-2-3-4 multiplier lamps until the full progression is lit.'],
['Lock the upper-left spinner at 4K','Set the upper-left spinner to 4,000 per spin.','The spinner value cycles; hit the three-bank to lock in the current value, aiming for 4K.'],
['Light and collect a lower spinner','Use a flipper rollover to light the opposite spinner, then shoot it.','A rollover lights the spinner across the playfield briefly; collect it before the light expires.'],
['Reach 10× with 47K base bonus','Build base bonus to 47K and multiplier to 10×.','Collect zodiac symbols for base bonus and complete the lower banks for multiplier; verify both indicators.']]
  };
  
return Object.assign({},classicRules,classicRules2);
})();
