window.PinheadRulePacks=Object.assign(window.PinheadRulePacks||{},(function(){return {
'combat':[
['Complete the target sequence','Complete the machine’s lit target sequence.','Follow the target lamps and hit the next required target; the objective is the completed sequence, not one random hit.'],
['Clear a target bank','Knock down a full bank of Combat drop targets.','Work the standing targets until the bank is completely down; confirm the bank reset/award.'],
['Collect a lit lane','Roll through a lit top lane.','Check the lane inserts before plunging or shooting up top and aim for the currently lit lane.'],
['Advance bonus','Earn five bonus advances during one ball.','Use the target and lane features that visibly advance the bonus count; verify the count before the ball ends.'],
['Complete two target sets','Complete two distinct target groups in one game.','Finish one target group fully before moving to the next; partial banks do not count.'],
['Collect a saucer award','Capture the ball in a lit saucer.','Use the saucer when its award is lit and confirm the ball is captured and the award registers.'],
['Light a feature award','Complete the target/lane requirement that lights a feature award.','Track the corresponding insert and only count the objective when the lamp changes to the lit state.'],
['Collect the feature award','Shoot the feature after its award is lit.','Once the feature insert lights, make the associated shot and confirm the machine awards it.'],
['Complete a target-and-lane combo','Complete a target group and a lit lane in the same game.','Clear the target group, then take the lit lane when the ball feeds safely.'],
['Maximize bonus','Reach the machine’s maximum displayed bonus.','Build bonus through the marked playfield features and confirm the maximum before the ball drains.']],
'firecracker':[
['Hit the Firecracker target feature','Make a successful shot at the central Firecracker feature.','Aim for the central labeled feature and verify the playfield registers the hit.'],
['Score five bumper hits','Register five pop-bumper hits in one ball.','Send the ball into the upper bumper area and count actual bumper switch hits.'],
['Complete the top lanes','Roll through all lit top rollover lanes.','Track the lane lamps and use the plunge/upper-playfield feed to complete the missing lanes.'],
['Collect a lit lane award','Roll through a top lane while its award is lit.','Check the top lane inserts before shooting up top.'],
['Advance bonus five times','Earn five bonus advances during one ball.','Use the lanes and targets that advance bonus and verify the count on the score/bonus display.'],
['Hit the same feature three times','Make three registered hits on the same named playfield feature.','Choose a repeatable labeled feature and count only successful registered hits.'],
['Complete a target group','Clear a complete drop-target group.','Focus on the remaining standing targets and confirm the full group is down.'],
['Collect a high-value feature','Qualify and collect the feature’s highest lit award.','Advance the feature until its highest-value lamp/award is lit, then make the collect shot.'],
['Complete lanes and target group','Complete the top lanes and clear one target group in one game.','Track both the lane inserts and target bank; finish both before game over.'],
['Reach maximum bonus and collect it','Maximize bonus and collect the available bonus award.','Build the bonus through the playfield features and use the marked collect feature if lit.']],
'lucky hand':[
['Complete a suit lane','Collect one of the four top suit lanes.','Uncollected suit lanes are lit; choose a suit lane you still need.'],
['Complete all four suit lanes','Collect all four top suit lanes.','Track each suit insert; the full set lights the 50K Wow and a repeating Wow lane.'],
['Complete the two Jacks','Knock down both Jack targets.','Follow the poker-hand sequence; the first hand is the two Jacks.'],
['Complete three Queens','Knock down all three Queen targets.','After Jacks, clear the three Queen targets to advance the poker hand.'],
['Complete a full house','Complete the Queens and Kings full-house targets.','Clear the three Queens and two Kings; confirm the hand advances.'],
['Complete the Royal Flush','Clear the five Royal Flush targets.','Follow the hand progression and finish all five Royal Flush targets.'],
['Collect a Wow award','Collect a lit 50K Wow award.','Complete the required suit/hand progress, then shoot the lit Wow lane/target.'],
['Complete two poker hands','Finish two successive poker-hand stages in one game.','After the first hand completes, follow the newly lit target group.'],
['Raise target value before a hand','Complete three suit lanes, then hit a drop target.','Drop-target value rises with completed lanes; complete three lanes before shooting the drops.'],
['Collect a repeat Wow','Complete Royal Flush, then collect a repeat Wow.','After Royal Flush, the targets light for repeat Wow awards; hit a lit target or lane.']],
'moon flight':[
['Complete the moon lanes','Complete the marked upper lanes that advance Moon Flight.','Track the moon/letter inserts and aim for whichever lane is still unlit.'],
['Hit the Moon Flight target','Make a successful shot to the Moon Flight target.','Use a controlled shot to the labeled Moon Flight feature and confirm the hit registers.'],
['Collect a lit saucer award','Capture the ball in the saucer when an award is lit.','Check the saucer award lamp first; the shot only counts if the saucer captures the ball.'],
['Advance the bonus sequence','Advance the bonus counter through five qualifying hits.','Use the marked targets and rollover lanes that increase bonus and verify the count.'],
['Complete a target bank','Clear a full drop-target bank.','Work the remaining standing targets and confirm the bank completion award.'],
['Collect a lane award','Roll through the currently lit lane.','Check the lane lamps before aiming up top; use a soft plunge if it helps reach the desired lane.'],
['Hit a feature twice','Register two successful hits on the same named Moon Flight feature.','Choose the repeatable labeled shot and count only confirmed switch hits.'],
['Complete lanes and target bank','Finish the lane sequence and clear one full target bank.','Track the lane inserts, then finish the full target bank before draining.'],
['Collect the high-value award','Advance the Moon Flight feature to its highest lit award and collect it.','Use the feature’s progress lamps to identify the top award before making the collect shot.'],
['Maximize bonus','Reach the maximum bonus shown by the machine.','Build bonus through the named lanes/targets and verify the maximum before end-of-ball.']],
'olympic hockey':[
['Complete the A lane','Roll through the A lane.','A lights the yellow upper-left and lower-right bumpers; confirm the A insert registers.'],
['Complete the B lane','Roll through the B lane.','B lights the red upper-right and lower-left bumpers; confirm the B insert registers.'],
['Open the right ball-save gate','Complete both A and B lanes.','The A/B combination opens the right-outlane ball-save gate; check that the gate is physically open.'],
['Advance the goal counter','Complete the goal-advance switches and score a goal.','Use the lanes, bumpers, rollover buttons and side lanes that advance the goal counter; follow the lit goal feature.'],
['Light the center bumper','Score a goal to light the center bumper for 1,000.','After a goal, hit the center bumper while its 1,000 lamp is lit; side-lane resets can turn it off.'],
['Score three lit center-bumper hits','Hit the center bumper three times while it is lit for 1,000.','After scoring a goal, aim for the edge of the center bumper and count registered hits before the feature resets.'],
['Hit both up-post targets','Hit the stand-up targets outside the A and B lanes.','These targets raise the center ball-save post; confirm each target registers.'],
['Score a goal and open the gate','Score a goal and complete A and B to open the gate.','Advance the goal, then complete both top lanes and verify the gate opens.'],
['Complete A and B twice','Complete both lanes two times in one game.','After the first set opens the gate, track the reset and finish both lanes again.'],
['Score two goals in one ball','Advance and score two goals before the ball drains.','Use the goal-advance sequence, then follow the lit goal feature for each goal.']],
'pop-a-card':[
['Collect the lit top lane','Roll through the currently lit top lane.','One top lane is lit for the skill shot; use a plunge strength that reaches it.'],
['Clear the left drop bank','Knock down all left-side drop targets.','Clearing a side set lights its matching bumpers and lanes for higher values.'],
['Clear the right drop bank','Knock down all right-side drop targets.','Finish the right bank and confirm its feature lamps change.'],
['Light the left-side feature','Complete the left drop set.','Watch for the left-side bumper and lane lamps to activate after the target bank clears.'],
['Light the right-side feature','Complete the right drop set.','Watch for the right-side bumper and lane lamps to activate after the target bank clears.'],
['Collect a 500-point lane','Roll through an upper lane while it is worth 500.','After clearing targets, send the ball up top and guide it into the lit lane.'],
['Complete both side banks','Clear the left and right drop-target sets.','Finish one bank fully, then work the other; confirm both are down.'],
['Hit both lower stand-up targets','Hit the lower-left and lower-right stand-up targets.','Aim carefully at the two lower stand-ups because their rebounds can drain.'],
['Complete the top target bank','Knock down all five top targets.','The full top bank lights the top side lanes and outlanes for the extra-ball feature when enabled.'],
['Collect a lit extra-ball feature','Complete the target requirement and collect the lit extra-ball award.','Extra-ball behavior depends on operator settings; verify the extra-ball lamp and award.']],
'quick draw':[
['Complete the Quick Draw target sequence','Complete the currently lit Quick Draw target sequence.','Follow the lit targets and make the next required hit rather than shooting a random target.'],
['Clear a target bank','Knock down a complete drop-target bank.','Finish every standing target in the chosen bank and confirm its completion award.'],
['Collect a lit lane','Roll through the currently lit top lane.','Check the lane inserts and aim for the uncollected/lit lane.'],
['Advance bonus five times','Earn five bonus advances in one ball.','Use the targets and lanes that advance the bonus count and verify progress.'],
['Complete two target groups','Clear two different target groups in one game.','Finish one group completely before switching to the next.'],
['Collect a saucer award','Capture the ball in a lit saucer.','Check the saucer award lamp and confirm the ball is captured.'],
['Complete the lane sequence','Collect all lanes in the indicated sequence.','Track the lane inserts and finish the missing lane before the ball drains.'],
['Collect a high-value target award','Hit a target when its highest-value lamp is lit.','Advance the target value through the machine’s lane/target feature, then shoot while lit.'],
['Complete a target and lane combo','Clear one target group and collect one lit lane.','Finish the target group first, then use the upper playfield to collect the lane award.'],
['Maximize end-of-ball bonus','Reach the maximum bonus displayed by the game.','Advance bonus through the named targets and lanes and avoid tilting before the bonus count.']],
'super-flite':[
['Collect the top saucer award','Capture the ball in the top saucer.','The saucer cycles awards; check the indicated gate/points award before shooting.'],
['Open the lower gate','Collect the saucer award that opens the lower gate.','Cycle the saucer award and shoot it when the lower-gate award is shown.'],
['Open the upper gate','Collect the saucer award that opens the upper gate.','Watch the saucer’s current award and collect the upper-gate state.'],
['Complete an A–D letter set','Collect all four letters in one letter set.','Work the letter features until A, B, C and D are all registered.'],
['Reach 2× bonus','Complete one A–D set to light 2× bonus.','Finish the four-letter set and confirm the 2× multiplier lamp.'],
['Reach 3× bonus','Complete two A–D sets to light 3× bonus.','Complete another full letter set and verify 3× is lit.'],
['Score the open lower gate','Send the ball through the lower gate while open.','When the lower gate is open, use the shot and confirm the 5,000-point award.'],
['Complete two letter sets','Finish two full A–D sets in one game.','Complete the first set, then track the reset and finish a second.'],
['Collect the saucer twice','Capture the top saucer twice in one game.','Check the current award before each saucer shot and confirm both captures register.'],
['Reach 3× and collect a gate award','Light 3× bonus and collect an open-gate award.','Finish two letter sets, then time the saucer for a gate-opening award.']],
'super spin':[
['Hit the spinner','Make a successful shot through the spinner.','Aim for the spinner lane and verify it spins/registers.'],
['Light the spinner','Complete the required target/lane feature to light the spinner.','Track the spinner insert and finish the required lane/target sequence.'],
['Collect a lit spinner award','Shoot through the spinner while its high-value lamp is lit.','Check the spinner lamp before shooting; the high-value award only counts while active.'],
['Complete the top lanes','Roll through all marked top lanes.','Use the upper-playfield feed and track which lane inserts remain unlit.'],
['Clear a drop-target bank','Knock down all targets in one drop bank.','Finish the remaining standing targets and confirm the bank is completely down.'],
['Advance bonus five times','Score five bonus advances in one ball.','Use the top lanes and targets that advance bonus; check the count before draining.'],
['Collect a saucer award','Capture the ball in the saucer when an award is lit.','Check the saucer’s current award and verify the ball is captured.'],
['Hit the spinner three times','Make three registered spinner shots in one game.','Use the repeatable spinner lane and count successful passes.'],
['Complete lanes and spinner','Finish the top lane set and collect a lit spinner shot.','Complete the lane feature first, then shoot the spinner while its award is active.'],
['Reach maximum bonus','Build bonus to its maximum displayed value.','Advance bonus with the marked targets and lanes, and confirm the maximum before end-of-ball.']]
};return p;})());