window.PinheadRulePacks=(function(){
var classicRules={
'abra ca dabra':[
['Collect number 1','Collect the 1 lane.','Watch the four numbered top lanes and aim for 1 if it is still missing.'],
['Collect number 2','Collect the 2 lane.','Use a controlled plunge or upper-playfield rebound to pass through lane 2.'],
['Collect number 3','Collect the 3 lane.','Check the number inserts first; collect 3 only if it has not registered this ball.'],
['Collect number 4','Collect the 4 lane.','A soft plunge can help reach 4; adjust the plunger strength to your machine.'],
['Complete 1–4','Collect all four numbered lanes in one ball.','Track each lane and prioritize whichever number remains unlit.'],
['Clear the ten-drop bank','Knock down all ten drop targets.','Target hits are worth more as the displayed bonus rises; finish the full bank.'],
['Reset the drop targets','Clear the ten-drop bank, then hit the center stand-up target.','The center target resets the bank after it is cleared, allowing another cycle.'],
['Hit a 5K target','Raise target value to 5K, then hit a drop target.','Collect numbered lanes to increase the displayed bonus before shooting the drops.'],
['Complete numbers and targets','Complete 1–4 and clear all ten drops in one ball.','Finish the missing lane first if possible, then clear the bank while maintaining control.'],
['Repeat the target cycle','Clear the ten-drop bank, reset it with the center target, and clear it again.','After the first bank is down, aim for the center reset target and repeat the target sequence.']],
'atlantis':[
['Hit a left drop-target pair','Knock down a pair of left-side drops with one shot.','The left drops are valuable in pairs; try a controlled cross-playfield shot from the right flipper.'],
['Collect the lit yellow lane','Roll through the currently lit yellow lane.','Top slingshot hits change the lit lane, so confirm the lamp before plunging or shooting.'],
['Advance the 1–9 sequence','Collect the next number in the 1–9 sequence.','Follow the number inserts; only the currently lit next number advances the sequence.'],
['Complete 1–9','Collect numbers 1 through 9.','Track the lit number and work through the sequence rather than chasing random lanes.'],
['Clear the left drop bank','Knock down every left-side drop target.','Use bank shots or a controlled shot from the right flipper; confirm the full bank is down.'],
['Clear the right drop bank','Knock down every right-side drop target.','Work the right bank when the return is favorable; fast balls on the right flipper can drain.'],
['Hit three enhanced targets','Score three hits while target-value lamps are lit.','Target pairs increase value; watch for the higher-value lamps before shooting.'],
['Collect a waterfall number','Send the ball through a lit number lane in the right waterfall.','The waterfall is risky near the lower-right exit; take the shot when the ball is controlled.'],
['Complete a number and a pair','Advance the next number and clear a left drop-target pair.','Do the lane when it is safely available, then return to the left drops.'],
['Complete sequence and bank','Complete the 1–9 sequence and clear one full drop bank.','This combines both main features; verify the final number and the cleared bank before game over.']],
'big brave':[
['Complete the three star rollovers','Roll through all three top star lanes.','Send the ball up top and track the three star inserts.'],
['Light double bonus','Complete all three top lanes to light double bonus.','Finish the remaining top lane and confirm the double-bonus lamp.'],
['Hit the vari-target','Shoot the vari-target and register its award.','Use a controlled shot; a miss can rebound toward the drain.'],
['Max the vari-target','Drive the vari-target to its maximum award.','A stronger accurate shot pushes the target farther; confirm the top award registers.'],
['Double bonus plus vari-target','Light double bonus, then hit the vari-target in the same ball.','Finish the three top lanes first, then take the vari-target when the shot is controlled.'],
['Clear the upper-left drops','Knock down the upper-left drop-target group.','Aim for the target faces and watch for dangerous center rebounds.'],
['Earn five bonus advances','Advance the end-of-ball bonus five times.','Work the upper playfield and top lanes, then check the bonus count.'],
['Collect a lit lane','Roll through a lane lit for an enhanced award.','Check the lane lamps before aiming up top.'],
['Complete the star lanes twice','Complete all three top star lanes two times in one game.','After the first completion, track the reset state and collect all three again.'],
['Max base bonus and double it','Reach maximum base bonus and activate double bonus.','Build bonus through upper-playfield activity, then finish the top lanes.']],
'centigrade 37':[
['Complete A–B–C–D','Register all four top letters.','Check the A, B, C and D inserts and finish whichever letters remain.'],
['Light the drop targets for 5K','Complete A–B–C–D to light the drop targets for 5K.','Finish the four-letter sequence and confirm the 5K target lamps.'],
['Clear the lit drop bank','Knock down the drop targets while their 5K feature is lit.','Complete A–D first, then shoot the bank while its higher value is active.'],
['Score the top saucer','Capture the ball in the top saucer.','The top saucer is a key shot from the left flipper; confirm the ball is captured.'],
['Collect a 5K return lane','Roll through a return lane lit for 5,000.','Track the lit lane and take it when the ball feeds safely.'],
['Letters plus saucer','Complete A–D and score the top saucer in the same ball.','Finish the letters, then shoot the saucer from a controlled flipper.'],
['Hit a lit bullseye','Hit a bullseye after its feature is lit.','Clear the required drops and check the bullseye insert before shooting.'],
['Complete A–D twice','Finish the four-letter sequence two times.','After the first set, follow the reset lamps and complete all four letters again.'],
['Clear two drop banks','Clear two distinct drop-target banks in one game.','Use the letter feature to raise target value, then clear each full bank.'],
['Max bonus and collect saucer','Build bonus to its maximum and collect it through the saucer.','Advance bonus on the upper playfield and use the saucer to collect the accumulated award.']],
'dimension':[
['Clear a color bank','Knock down all five drop targets of one color.','A completed color set lights its matching saucer and lane; track the five targets in that bank.'],
['Collect a matching saucer','Complete a color bank, then collect that color’s saucer.','Clear all five same-color drops, then shoot the newly lit top saucer.'],
['Collect a matching lane','Complete a color bank and roll through its matching lane.','After clearing the color bank, use upper-playfield flow to collect its lane award.'],
['Complete the green bank','Clear the five green drop targets.','Green is one of the upper colors; its completed set lights a return lane and saucer.'],
['Complete the red bank','Clear the five red drop targets.','Track the red bank and confirm all five targets are down.'],
['Complete the yellow bank','Clear the five yellow drop targets.','Finish the full yellow bank and check its matching lamps.'],
['Complete the blue bank','Clear the five blue drop targets.','Finish the full blue bank and check its matching lamps.'],
['Advance bonus multiplier','Complete the top three lanes to advance multiplier.','Watch the top lane inserts and finish the set to advance the bonus multiplier.'],
['Reach 5× multiplier','Advance the bonus multiplier to 5×.','Repeat the top-lane feature until 5× is lit.'],
['Collect two color saucers','Complete two color banks and collect both matching saucers.','Work one color set at a time and collect each corresponding saucer award.']],
'drop-a-card':[
['Collect the lit top lane','Roll through the currently lit top lane.','One top lane is lit for the skill shot; use the appropriate plunge strength.'],
['Clear the left drop bank','Knock down all left-side drop targets.','Clearing a side set lights its matching bumpers and lanes for higher values.'],
['Clear the right drop bank','Knock down all right-side drop targets.','Finish the right bank and confirm its feature lamps change.'],
['Light the left-side feature','Complete the left drop set to light its bumpers and lanes.','Track the left target bank and look for the matching lane and bumper lamps.'],
['Light the right-side feature','Complete the right drop set to light its bumpers and lanes.','Track the right target bank and look for the matching lane and bumper lamps.'],
['Collect a 500-point top lane','Roll through one of the upper 500-point lanes.','After clearing targets, send the ball up top and guide it into a 500 lane.'],
['Complete both side banks','Clear the left and right drop-target sets.','Target progress is retained; finish one bank and then the other.'],
['Hit both lower stand-ups','Hit the lower-left and lower-right stand-up targets.','These targets matter once the drops are cleared; take care with target rebounds.'],
['Score five bumper hits after drops','Clear the target sets, then score five bumper hits.','Once the drops are down, send the ball up top and count registered bumper hits.'],
['Complete lane and both banks','Collect a lit top lane and clear both side target banks.','Take the lit lane when available, then complete the two banks.']],
'jacks open':[
['Collect one suit lane','Complete one of the four top suit lanes.','Uncollected suit lanes are lit; choose a lane you still need.'],
['Collect three suit lanes','Complete three of the four top suit lanes.','Drop-target value rises with the first three completed lanes, so track lane progress.'],
['Complete all four suit lanes','Collect all four top suit lanes.','Completing the fourth resets the lanes and lowers drop value; verify the reset.'],
['Complete two Jacks','Knock down both Jack targets.','The first poker hand is two Jacks; clear both J targets.'],
['Complete three Queens','Knock down all three Queen targets.','After the Jacks, clear the three Queen targets to advance the hand.'],
['Complete a full house','Complete three Queens and two Kings.','Finish the Queen group and both King targets; confirm the hand advances.'],
['Complete the Royal Flush','Clear all five Royal Flush heart targets.','Follow the poker-hand progression and finish all five heart targets.'],
['Complete a hand award','Finish one poker-hand stage.','Follow the target sequence: Jacks, Queens, full house, then Royal Flush.'],
['Raise target value first','Complete three suit lanes, then hit a drop target.','Build lane progress before shooting drops; completing the fourth lane resets the lane set.'],
['Complete two hand stages','Finish two successive poker-hand stages in one game.','After a hand completes, follow the newly required target group.']],
'jet spin':[
['Hit the roto target','Make a successful shot to the central roto target.','The roto target is the main repeatable feature; aim from the right flipper.'],
['Hit the left bullseye','Hit the narrow left bullseye target.','Use a controlled shot from the right flipper and watch the rebound.'],
['Score the right saucer','Capture the ball in the right-side saucer.','Take the saucer shot when the ball is controlled and verify it captures.'],
['Earn five bonus advances','Score five bonus advances in one ball.','The roto target can award multiple advances; track the bonus count.'],
['Max the 15K bonus','Reach the 15K base-bonus maximum.','Use the roto target and upper features to advance bonus; confirm the counter reaches 15K.'],
['Hit the roto target three times','Make three roto-target shots in one game.','Favor the repeatable roto target and count successful registered hits.'],
['Collect a lit top lane','Roll through a currently lit top lane.','Check the lane lamps before plunging or shooting up top.'],
['Hit roto and bullseye','Score both the roto target and left bullseye in one game.','Prioritize the safer roto shot and attempt the narrow bullseye from a controlled right-flipper position.'],
['Target then saucer','Hit a target, then collect the saucer award in the same ball.','Recover the target rebound and take the saucer if the return path is safe.'],
['Hit the roto target five times','Make five successful roto-target shots in one game.','Stay with the main roto target and count only confirmed hits.']]
  };
  
var classicRules2={
'jungle queen':[
['Clear one side drop bank','Knock down all five drops on one side.','Use the upper mini-flippers to direct the ball to the side drops, then finish the remaining targets.'],
['Light a 5K side lane','Clear a side’s five drops to light its 5K lane.','Complete all five targets on the same side and confirm the matching lane lights.'],
['Collect a lit side lane','Roll through a side lane after it lights for 5K.','After a bank is cleared, aim for its corresponding lane when the ball feeds safely.'],
['Score an upper saucer','Capture the ball in either upper saucer.','A cleared side bank makes its upper saucer a valuable target; confirm capture.'],
['Complete A-B-C','Collect the A, B and C lanes.','Track the three letters; the full set doubles bonus.'],
['Activate double bonus','Complete A-B-C to light double bonus.','Finish the last missing letter and verify the double-bonus feature is active.'],
['Clear both side banks','Clear both five-target banks in one game.','Complete one side, then the other; each side lights its own 5K lane.'],
['Collect both 5K lanes','Light and collect both side lanes.','Clear both banks first, then collect each lit lane award.'],
['A-B-C plus a target bank','Light double bonus and clear a side bank in one ball.','Complete the three letters and all five drops on one side before draining.'],
['Collect both upper saucers','Capture the left and right upper saucers in one game.','Use the saucers above the cleared target banks and confirm both awards.']],
'lawman':[
['Open the waterfall gate','Hit the stand-up target right of the waterfall lanes.','The gate-opening target sits to the right of the waterfall; confirm the gate opens before attempting the waterfall.'],
['Shoot the waterfall with gate open','Send the ball through the right waterfall while the gate is open.','Open the gate first, then shoot the upper-right waterfall and watch the lower-right exit.'],
['Clear the left drop bank','Knock down the complete left drop-target bank.','A full bank completion is worth more than scattered target hits; verify every drop is down.'],
['Collect a lit waterfall lane','Roll through a currently lit waterfall lane.','Top and waterfall bonus lanes are synchronized; check which lane is lit before shooting.'],
['Repeat the waterfall pass','Make two waterfall passes with the gate open.','The gate can close after switch hits, so check its state before the second attempt.'],
['Advance bonus to 1,000','Advance the bonus reel to the 1,000 value.','Scoring points advances bonus; track the reel and preserve the bonus by avoiding a tilt.'],
['Clear both side target banks','Complete the left and right drop-target banks.','Finish one bank fully before moving to the other; the completion award registers when the bank clears.'],
['Collect a lane and clear a bank','Collect one lit waterfall lane and complete one drop bank.','Take the lane when safely available, then clear a full bank.'],
['Collect final-ball double bonus','Reach the final ball and collect double bonus.','Build bonus through targets and lanes, then avoid tilting during the final-ball bonus count.'],
['Open gate, waterfall, and return','Open the gate, make a waterfall pass, and return to the main playfield.','The open gate is what makes the waterfall exit survivable; confirm the ball returns to the main playfield.']],
'black hole':[
['Open the re-entry gate','Complete the four lower-right stand-up targets and open the gate.','Clear all four targets, then get the ball through the lane beneath them; verify the gate is open before visiting the lower playfield.'],
['Clear the main target bank','Complete the main-level target bank.','Finishing this bank also lights the main-level captive-ball hole and helps qualify a lock.'],
['Lock a lower-playfield ball','Lock a ball in the lower-left lock.','Send the ball to the lower level and shoot the lower-left lock; this lock can retain a ball between player turns.'],
['Lock an upper ball','Lock a ball at the main-level lock above the upper-left flipper.','Qualify the lock through the target bank or lower-playfield feature, then shoot the lit lock.'],
['Start lower-level multiball','Lock two balls and send a third ball to the lower playfield.','Once both locks are occupied, plunge the third ball to release the lower lock and start lower-level multiball.'],
['Return from the lower playfield','Open the gate and successfully return a ball from below.','The lower-playfield exit returns safely only while the re-entry gate is open.'],
['Light 2× lower-playfield scoring','Complete one upper drop-target bank.','One upper bank lights 2× on the lower playfield; verify the multiplier when you get downstairs.'],
['Light 3× lower-playfield scoring','Complete both upper drop-target banks.','Finish both banks to light 3× lower-playfield scoring.'],
['Advance lower-playfield bonus multiplier','Complete the top three lanes or the lower-right rollunder.','The lower-level rollunder and upper top lanes advance the bonus multiplier; use whichever shot is available.'],
['Complete the lock sequence','Lock two balls and start multiball via the lower playfield.','Qualify and secure both locks, then send the third ball to the lower level to trigger multiball.']],
'centaur':[
['Spell O-R-B-S in order','Complete the O-R-B-S drop targets in order.','Hit O, then R, then B, then S; an out-of-order hit resets the required sequence.'],
['Start Centaur multiball','Complete ORBS and shoot a release target.','ORBS builds virtual locks; hit the upper-right release target or the target behind the captive-ball drops to release locked balls.'],
['Complete 1-2-3-4 in order','Hit the numbered targets in sequence.','Follow 1, 2, 3, 4 in order to increase bonus advances and enable collect-bonus/release features.'],
['Collect bonus at the upper-right target','Light and hit the upper-right collect-bonus target.','Complete 1-2-3-4 in order, then shoot the lit upper-right target while the bonus award is ready.'],
['Reach 5× bonus multiplier','Complete the top three lanes until 5× is lit.','Use lane change to select missing top lanes; the multiplier advances through repeated lane sets.'],
['Hit the captive ball','Make a successful captive-ball shot.','Aim at the left captive ball; crossing the two left-arc star rollovers first doubles the shot value.'],
['Complete all four bottom lanes','Collect all four return/outlanes with lane change.','The flipper buttons change the left and right lane lamps independently; track the four lit inserts.'],
['Trigger multiball with the fourth lane','Complete three bottom lanes and drain through the fourth while a ball is locked.','With one ball locked, the fourth lane can trigger multiball if the other three lanes are already complete.'],
['Collect a 5× bonus award','Time the collect-bonus shot for its 5× multiplier.','Watch the lane leading to the collect target and shoot when the timed multiplier reaches 5×.'],
['Start multiball and hit captive ball','Start multiball, then hit the captive ball.','Complete ORBS/release to start multiball, then use a controlled shot on the captive ball.']],
'firepower':[
['Light the spinner','Complete the required numbered target sets to light the spinner.','Hit the center numbered stand-ups; settings may require one or both sets, so use the spinner insert as confirmation.'],
['Light the kickback','Complete the targets that qualify the left kickback.','Depending on the game settings, numbered targets or blue POWER targets may control the kickback; watch its lamp.'],
['Lock a ball','Qualify and shoot the lit lock saucer.','Complete the target set required by the machine, then shoot the lit lock saucer near the upper-left flipper.'],
['Start multiball','Lock the required balls and start multiball.','Follow the lock lamps and make the displayed start/release shot when the required balls are locked.'],
['Complete F-I-R-E','Collect all four top F-I-R-E lanes.','Track the four top lane inserts; lane change can help select missing letters.'],
['Complete the blue POWER targets','Hit all three blue POWER stand-up targets.','Shoot each of the three blue targets; completing the set lights return lanes and advances bonus.'],
['Reach 5× bonus multiplier','Complete top lane sets until 5× bonus is lit.','Each complete F-I-R-E lane set advances the multiplier up to 5×.'],
['Increase the center-target award','Complete FIRE and POWER sets, then hit the center target.','The center target between the I and R lanes increases in value as both feature sets are completed.'],
['Collect a lit spinner award','After lighting the spinner, shoot through it.','Use the right flipper for the spinner when lit and confirm the higher-value state.'],
['Light kickback and spinner','Complete the target features that light both kickback and spinner.','Track numbered and POWER targets; settings vary, so confirm both inserts are lit rather than assuming.']],
'flash gordon':[
['Reach 2× multiplier','Hit the second right-side inline target to light 2×.','Work the right inline drops and verify the 2× bonus lamp.'],
['Reach 3× multiplier','Hit the third right-side inline target to light 3×.','Complete the right inline progression and check the multiplier insert.'],
['Reach 4× multiplier','Clear the upper-playfield drop bank.','Finish the upper target bank; the 4× multiplier lamp confirms the step.'],
['Reach 5× multiplier','Clear the lower-left target bank.','After 2×, 3× and 4×, clear the lower-left bank and confirm 5×.'],
['Light the left spinner','Complete the lower-left target bank once.','The first completion lights the left spinner; shoot it while lit.'],
['Light the right spinner','Complete the lower-left target bank a second time.','Repeat the bank and check the right spinner insert.'],
['Activate a playfield multiplier','Qualify 2× or 3× playfield scoring and shoot the center saucer.','Complete the upper flashing targets for 2× or lower targets for 3×, then capture the center saucer.'],
['Collect the flashing upper-bank bonus','Complete the upper target bank while it is flashing.','Watch for the flashing bonus state and clear the whole bank before the targets reset.'],
['Collect bonus from the upper playfield','Knock down the single target above the upper flipper to route to the plunger lane.','The upper target enables a bonus-collect route; follow the ball back to the plunger lane and confirm collection.'],
['Qualify both playfield multipliers','Complete the upper and lower flashing target features.','Finish the upper feature for 2× and the lower feature for 3×; the center saucer activates the multiplier.']],
'quicksilver':[
['Clear the right three-bank','Knock down all three right-side drop targets.','The bank is a priority: one sweeping shot can clear several targets and feed the spinner.'],
['Reach 5× bonus multiplier','Complete the right three-bank progression until 5× is lit.','Keep working the right bank and watch the multiplier inserts for 5×.'],
['Collect a lit spinner','Light the opposite spinner with a return lane and shoot it before it times out.','Spinner lights are temporary; use a flow shot as the ball returns rather than waiting for a cradle.'],
['Clear the center four-bank','Knock down all four center drop targets.','Completing the center bank raises the left saucer value and spots a letter.'],
['Collect the left saucer award','Raise the saucer value with the center bank, then capture the saucer.','Confirm the value has increased, then shoot the saucer and verify the award.'],
['Advance base bonus','Use top lanes and lettered stand-up targets to advance bonus.','Watch the bonus count after each top-lane or lettered-target hit.'],
['Light both opposite spinners','Use both return lanes to light their opposite spinners.','Each return lane lights the opposite spinner only briefly; collect both before the lamps expire.'],
['Score three lit spinner turns','Score at least three spinner turns while lit.','Take the lit spinner immediately and verify the higher-value feature is active.'],
['Reach 75K base bonus','Build base bonus to its 75K maximum.','Use top lanes and lettered stand-ups; confirm the base bonus counter reaches 75K.'],
['Reach 5× and collect spinner','Reach 5× bonus and collect a lit spinner shot.','Complete the multiplier progression, then use a return lane to light and collect the spinner.']],
'seawitch':[
['Complete the center target bank','Clear the center drop bank to start multiplier progression.','Finish the center bank; this is the first step in the target-bank sequence.'],
['Reach 3× multiplier','Complete the left target bank after the center bank.','Follow the bank order: center advances to 2×, left to 3×.'],
['Reach 4× multiplier','Complete the top target bank after the earlier banks.','Finish the top bank in sequence and verify 4× is lit.'],
['Reach 7× multiplier','Repeat the target-bank sequence until 7× is lit.','Continue center, left, top bank progression and check the multiplier lamps.'],
['Increase spinner value','Hit all four upper star stand-up targets.','Each upper star increases spinner value; complete all four for the highest value.'],
['Collect a lit spinner','Shoot through the spinner after lighting its higher value.','Check the spinner insert and take the shot while the award is active.'],
['Complete all three banks','Clear center, left and top banks in one ball.','Finish each full bank; all three completed on the same ball light double value on loops.'],
['Collect a doubled loop','Complete all three banks, then score a loop shot.','After the banks light the doubler, shoot through the top star rollover to collect the doubled loop value.'],
['Reach 39K base bonus','Build base bonus to its 39K maximum.','Use targets and lanes to advance bonus and check the count before end-of-ball.'],
['Score two lit loop awards','Collect two loop awards while loop value is active.','Complete target banks to raise loop value, then shoot through the top star rollover.']],
'sorcerer':[
['Lock a ball at the left ramp','Make the left ramp shot to lock a ball.','The left ramp is the main lock shot; two successful lock-ramp shots normally qualify multiball.'],
['Start Sorcerer multiball','Complete the lock-ramp sequence and start multiball.','Lock the required balls with the left ramp and confirm multiball starts.'],
['Reach 5× playfield multiplier','Shoot the lock ramp during multiball until 5× is lit.','The multiplier advances 2×, 3×, then 5×; make the lit lock-ramp shot each time.'],
['Spell S-O-R-C-E-R-O-R','Complete all letters in SORCEROR.','Work the letter features when safe; finishing the word lights the spinners.'],
['Collect a lit spinner during multiball','During multiball, shoot a lit spinner.','Complete SORCEROR to light the spinners, then collect one during multiball.'],
['Complete A-B-C-D lanes','Roll through all four top lanes.','Track the top lane inserts; the completed set advances the bonus multiplier.'],
['Reach 8× bonus multiplier','Complete top-lane sets until 8× is lit.','The A-B-C-D lanes advance bonus through 2×, 4×, 6× and 8×.'],
['Clear the upper-right three-bank','Clear all three upper-right drops before they reset.','The bank is timed; finish it before the targets reset to collect the award.'],
['Collect hold bonus','Clear the upper-right bank while hold bonus is lit.','Check the hold-bonus indicator, then finish the timed three-bank.'],
['Start multiball and reach 5×','Start multiball and advance playfield multiplier to 5×.','Lock balls with the left ramp, then repeat the lit ramp shot during multiball.']],
'star gazer':[
['Collect one zodiac symbol','Hit a lit zodiac drop target.','The twelve drop targets represent zodiac symbols; shoot one that is still lit.'],
['Complete all twelve zodiac symbols','Collect all twelve zodiac symbols.','Work the lit zodiac targets and rollover letters until all twelve register.'],
['Light 12K Super Bonus','Complete the first full zodiac set.','Collect all twelve symbols and verify the 12K Super Bonus lamp.'],
['Light 24K Super Bonus','Complete a second zodiac set.','After the first set, continue collecting symbols until 24K Super Bonus lights.'],
['Light 36K Super Bonus','Complete a third zodiac set.','Continue the zodiac collection until the 36K Super Bonus lamp lights.'],
['Advance bonus multiplier','Complete one of the lower two drop banks.','The lower banks advance the multiplier; clear a bank and check the multiplier lamps.'],
['Reach 10× multiplier','Complete the lower-bank progression to reach 10×.','Follow the 1-2-3-4 multiplier lamps until the full progression is lit.'],
['Lock the upper-left spinner at 4K','Set the upper-left spinner to 4,000 per spin.','The spinner value cycles; hit the three-bank to lock in the current value, aiming for 4K.'],
['Light and collect a lower spinner','Use a flipper rollover to light the opposite spinner, then shoot it.','A rollover lights the spinner across the playfield briefly; collect it before the light expires.'],
['Reach 10× with 47K base bonus','Build base bonus to 47K and multiplier to 10×.','Collect zodiac symbols for base bonus and complete the lower banks for multiplier; verify both indicators.']]
  };
  
return Object.assign({},classicRules,classicRules2);
})();

window.PinheadRulePacks=Object.assign(window.PinheadRulePacks||{},(function(){var p={
'attack from mars':[
['Complete MARTIAN','Complete the MARTIAN target sequence.','Hit the MAR targets and the T, I and AN targets; track the letters until MARTIAN is complete.'],
['Lower the saucer force field','Hit all three force-field targets in front of the saucer.','Clear the three force-field targets; the field drops and Attack Phase begins.'],
['Destroy a flying saucer','Damage the saucer targets, then shoot the hole behind the rear drop target.','During Attack Phase, hit the inner saucer targets until the rear drop stays down, then shoot the hole.'],
['Complete an Attack Phase','Destroy one country’s flying saucer.','Lower the force field, hit the exposed saucer targets, then finish with the hole shot.'],
['Start Martian Attack','Qualify Martian Attack and collect it at the scoop.','Complete the Martian targets or qualify the feature through Stroke of Luck, then shoot the scoop.'],
['Defeat all four Martians','Hit all four dancing Martians before the timer expires.','Hit the target bank beneath each Martian during the timed mode.'],
['Start regular multiball','Lock three balls at the middle orbit.','Shoot the middle orbit to light lock, then lock three balls; the third lock starts multiball.'],
['Collect a Super Jackpot','Collect all regular jackpots, then hit the moving Super Jackpot.','During multiball, complete the lit left orbit, left ramp, middle orbit, right ramp and right orbit jackpots; then chase the moving Super Jackpot.'],
['Complete Total Annihilation','Complete Capture, Big-O-Beam, Tractor Beam and Atomic Blaster.','Make three shots each at the left orbit, left ramp, right ramp and right orbit; then complete the saucer hurry-up.'],
['Rule the Universe','Complete the required major features and start Rule the Universe.','This expert goal requires a Super Jackpot, Super Jets, Martian Attack multiball, Total Annihilation, conquering Mars, and a five-way combo.']],
'big bang bar':[
['Complete B-A-R','Collect all three B-A-R rollover lanes.','Use lane change to aim for the unlit letter; completing all three advances bonus multiplier up to 5×.'],
['Qualify a Bar Room Brawl mode','Clear the center three-bank, then shoot the ramp.','The center bank qualifies the next mode; the ramp starts the selected mode.'],
['Complete Mash A Go-Go','Start Mash A Go-Go and complete its bumper objective.','Qualify the mode, shoot the ramp, then work the pop bumpers as instructed by the display.'],
['Complete Cosmic Dartz','Start Cosmic Dartz and finish its dart challenge.','Qualify Cosmic Dartz, shoot the ramp to start, and follow the display prompts.'],
['Start Looped in Space','Clear the left four-bank and lock a ball.','The left four-bank enables the left alien-ball lock; finish it and shoot the lit lock.'],
['Start Multi-brawl','Spell B-R-A-W-L on the captive-ball feature and complete the lock sequence.','Hit the flashing side of the four-ball captive-ball turnaround to collect letters; complete BRAWL and follow the lock lamps.'],
['Light Tube Dancer','Hit all three green stand-up targets.','The three green stand-ups around the ramp and upper orbit qualify Tube Dancer.'],
['Collect a Tube Dance jackpot','Shoot the ramp while Tube Dancer is active.','When the tube dancer is lit and dancing, the ramp becomes the jackpot shot.'],
['Collect an Underground award','Hit the Doorman drop target while Underground is qualified.','The Doorman is the single drop below the BAR lanes; shoot it when Underground is active.'],
['Start The Big Bang','Complete the other modes/features, then hit the Doorman target.','The Big Bang is the ultimate challenge; finish the other modes/features and shoot the Doorman when lit.']],
'cirqus voltaire':[
['Raise the Ringmaster','Qualify and raise the Ringmaster toy.','Work the Ringmaster feature and follow the display/insert sequence.'],
['Start Ringmaster Frenzie','Qualify and start Ringmaster Frenzie.','Shoot the required Ringmaster shots and confirm Frenzie starts on the display.'],
['Defeat the Ringmaster','Complete Ringmaster Battle by hitting the Ringmaster repeatedly.','After the fifth Ringmaster is defeated, keep hitting him; long gaps let him recover progress.'],
['Complete Strike-an-Arc','Complete the Strike-an-Arc feature.','Follow the lit feature shots and display instructions to advance Strike-an-Arc.'],
['Start multiball','Qualify and start a named Cirqus multiball.','Follow the active lock/multiball inserts and use the indicated shot to start it.'],
['Complete one Marvel','Finish one of the game’s Marvel features.','Watch the display for the current Marvel objective and complete its required shots; starting alone does not count.'],
['Complete three Marvels','Finish three different Marvel features in one game.','Track which Marvels are completed and choose available ones; confirm each completion on the display.'],
['Start Ringmaster Battle multiball','Defeat the fifth Ringmaster and start the battle.','Ringmaster Battle begins after the fifth Ringmaster; keep hitting the toy to prevent recovery.'],
['Defeat the Ringmaster in battle','Finish Ringmaster Battle and defeat the Ringmaster.','Keep both balls available and continue landing Ringmaster hits; the battle is not completed merely by starting it.'],
['Join the Cirqus','Complete the required Marvels to start Join the Cirqus.','Finish the Marvel collection and follow the display’s final wizard-mode sequence.']],
'funhouse':[
['Advance the clock to midnight','Advance the clock to 12:00.','Use the clock-advancing shots and track the clock; midnight qualifies the Rudy mouth lock.'],
['Start Midnight Multiball','Lock a ball in Rudy’s open mouth at midnight.','When the clock reads midnight and Rudy opens his mouth, shoot the mouth to lock the ball and start multiball.'],
['Score a Rudy Gulp','Shoot into Rudy’s open mouth while he is talking.','Listen for Rudy’s speech and shoot during the open-mouth window.'],
['Hit Rudy’s jaw','Hit Rudy’s jaw from the side flipper.','A jaw hit adds end-of-ball bonus and relights the Mirror award.'],
['Collect the Mirror award','Relight and collect the Mirror feature.','Hit Rudy’s jaw to relight Mirror, then shoot the Mirror feature when available.'],
['Make the trapdoor loop','Make a successful trapdoor loop shot.','Aim for the trapdoor loop and verify the feature registers.'],
['Reach 11:30 twice','Advance the clock to 11:30 for a second time.','The second arrival lights the outlane Special lamps; collect the lit award before the ball ends.'],
['Collect an outlane Special','Drain through an outlane while its Special lamp is lit.','After the second 11:30, slingshot hits toggle the Special lamps; the award must be collected before the ball ends.'],
['Hit Rudy’s jaw three times','Make three Rudy jaw hits in one game.','Use the side flipper to hit the jaw and track the bonus progression.'],
['Start and score Midnight Multiball','Start Midnight Multiball and score a feature shot during it.','Lock the ball in Rudy’s mouth at midnight, then make a lit shot while both balls are active.']],
'medieval madness':[
['Destroy a castle','Lower the drawbridge, raise the gate, then shoot the Main Entrance.','Hit the Drawbridge the required number of times, hit the lowered Gate the required number, then shoot the entrance.'],
['Destroy two castles','Destroy two different castles during one game.','Repeat the drawbridge, gate and entrance sequence for the next castle.'],
['Collect a Castle Hurry-Up','Complete a required row of lights and collect at the Main Entrance.','The hurry-up counts down quickly; shoot the Main Entrance before it expires.'],
['Start Trolls!','Qualify and start Trolls!','Follow the troll-feature lamps and display prompts until the mode starts.'],
['Start Multiball Madness','Complete the required feature qualification and start Multiball Madness.','Follow the multiball inserts and make the lit start shot; verify the mode name on the display.'],
['Start Royal Madness','Progress through the required castle and multiball features to start Royal Madness.','Complete the preceding wizard-mode requirements and follow the final qualification on the display.'],
['Collect a Merlin award','Shoot Merlin’s saucer while an award is lit.','Use the lit saucer to collect the available award, including an extra ball when qualified.'],
['Light Castle Crusher','Destroy all six castles, including the King of Payne’s castle.','Repeat the drawbridge, gate and Main Entrance sequence; the King’s castle is last and takes more hits.'],
['Start Battle for the Kingdom','Complete the Castle Crusher requirements and start the final battle.','Finish the castle progression and follow the Battle for the Kingdom start indication.'],
['Collect the castle extra ball','Destroy the required castles and collect the lit extra ball at Merlin’s saucer.','The default rules light an extra ball after two castles; shoot Merlin’s saucer while the award is lit.']],
'scared stiff':[
['Start a tale','Start one of the six tales.','Use the tale’s qualifying shots and start feature; confirm the tale begins on the display.'],
['Complete all six tales','Start all six tales to qualify Scared Stiff.','Track the six tale lamps and complete each tale’s required shots; finishing all six lights the crate.'],
['Start Scared Stiff','After all six tales, hit the crate.','Once all six tale lamps are complete, shoot the crate and confirm the Stiff-O-Meter starts.'],
['Advance the Stiff-O-Meter','Complete one alternating ramp/crate step.','The sequence alternates ramp, crate, ramp, crate; follow the order shown by the feature.'],
['Max the Stiff-O-Meter','Advance the meter to level 10.','Keep alternating ramp and crate shots until the meter reaches its top level.'],
['Collect the Stiff-O-Meter award','Hit the crate to collect the current meter award.','During the crate mode, the meter rises and falls; shoot the crate to collect the current multiplied value.'],
['Collect the left-ramp jackpot','Light the left-ramp jackpot and shoot the ramp.','A Stiff-O-Meter award can light the left ramp for a 250K jackpot; collect it while lit.'],
['Collect all three Eye awards','Complete the three Eye awards.','Track each Eye award and finish the missing requirements; all three Eyes light an extra ball.'],
['Collect Double Trouble','Activate Double Trouble and score during its 20-second window.','Every shot is doubled for 20 seconds; prioritize safe repeatable shots while the timer runs.'],
['Start Scared Stiff and reach level 10','Start the mode and max the Stiff-O-Meter.','Complete all six tales, hit the crate, then alternate ramp and crate shots until level 10.']]
};return p;})());

window.PinheadRulePacks=Object.assign(window.PinheadRulePacks||{},(function(){var p={
'creature from the black lagoon':[
['Complete the Snack Bar sequence','Complete the Snack Bar target sequence.','Work the Snack Bar targets and follow the inserts to advance the feature; verify the sequence completes.'],
['Start Creature Feature','Qualify and start Creature Feature.','Build the required feature progress, then shoot the lit start shot shown by the machine.'],
['Collect a film award','Collect one lit film or movie award.','Use the currently lit movie feature and confirm the display awards it; do not count an ordinary shot.'],
['Start multiball','Qualify and start the game’s multiball feature.','Follow the lock/feature lamps and make the lit start shot; verify multiball begins.'],
['Collect a jackpot','During multiball, shoot the lit jackpot shot.','Start multiball and aim for the currently lit jackpot; check the display for the award.'],
['Complete a ramp feature','Make a successful shot up the ramp while its feature is lit.','Watch the ramp insert and shoot only when the corresponding feature is active.'],
['Collect a lit extra ball','Qualify and collect the extra ball award.','Complete the machine’s extra-ball qualification and shoot the lit award location shown by the inserts.'],
['Complete the Snack Bar and film feature','Complete Snack Bar progress and collect a film award in one game.','Track both the Snack Bar inserts and the active movie feature; finish each distinct objective.'],
['Collect two multiball jackpots','Collect two separate jackpots during multiball.','Keep multiball alive and follow the lit jackpot shots; each award must register separately.'],
['Complete Creature Feature and collect its award','Finish Creature Feature and collect its completion award.','Follow the mode’s lit shots to the completion indication, then make the award shot if the display requests one.']],
'indiana jones: the pinball adventure':[
['Complete Path of Adventure letters','Complete all letters in ADVENTURE.','Hit the individual letter targets or the lit ADV, ENT and URE groups; completed groups spot the next unlit letter.'],
['Start Path of Adventure','Complete ADVENTURE and shoot the right ramp.','When all ADVENTURE targets are complete, the right ramp lights; shoot it before the 15-second qualification expires.'],
['Collect a Path of Adventure rollover','On the raised mini-playfield, roll over one lit yellow lane.','Steer the raised playfield left/right to cross a lit yellow rollover; the number lit increases with repeated completions.'],
['Collect the Pit award','During Path of Adventure, send the ball into The Pit hole.','The raised playfield has a Pit hole; choose it only if you want the Pit award rather than continuing rollover progress.'],
['Collect the Path extra ball','Complete a rollover set to light the extra-ball hole, then collect it.','During Path of Adventure, collect the first set of rollovers; the extra-ball hole can light after the set.'],
['Start a mode from the ramp','Shoot a lit ramp to select/qualify a mode, then start it.','Use the ramp shots to advance/select modes, then shoot the Start Mode shot shown by the game.'],
['Collect a Dogfight award','Shoot the sinkhole while Dogfights are lit.','Ramp shots can light Dogfights; shoot the sinkhole to collect the available Dogfight award.'],
['Collect Hand of Fate','Light Hand of Fate and collect it at the start shot.','Use the ramp/mode progression to light Hand of Fate, then make the displayed start/collect shot.'],
['Complete a mode','Finish one named Indiana Jones mode.','Follow the mode’s lit shots and display prompts until the game confirms completion.'],
['Start Eternal Life multiball','Qualify and start Eternal Life multiball.','Build the required multiball progression and use the lit start shot; verify the mode begins.']],
'star trek: the next generation':[
['Complete a mission','Complete one of the seven standard missions.','Watch the STTNG emblems at shot entrances; make the flashing required shots for the currently selected mission.'],
['Complete two missions','Finish two different standard missions.','The bumpers and Q target advance the lit mission; track completed missions on the display.'],
['Collect an artifact','Collect one of the four artifacts.','Follow the artifact feature; the computer announces when a Singing Stone, Isolinear Chip, Diranium Sphere or Dilithium Crystal is collected.'],
['Start Final Frontier','Complete all seven missions to start Final Frontier.','Finish each of the seven standard missions; the eighth mission, Final Frontier, then becomes available.'],
['Play the Holodeck','Start and complete a Holodeck feature.','Shoot the Holodeck when it is lit and follow the simulated challenge instructions on the display.'],
['Start multiball','Qualify and start multiball.','Follow the lock and multiball inserts and use the lit shot to start the mode.'],
['Collect a jackpot','During multiball, collect a lit jackpot.','Make the current jackpot shot and confirm the award on the display.'],
['Collect two artifacts','Collect two distinct artifacts in one game.','Track the artifact announcements and repeat the required feature for a second artifact.'],
['Complete Final Frontier','Start Final Frontier and finish its required shot sequence.','After all seven missions, follow the Final Frontier instructions and complete the lit shots.'],
['Complete a mission and collect an artifact','Finish a mission and collect an artifact in one game.','Use the lit mission shots for the mission completion, then follow the artifact feature until the display confirms it.']],
'tales of the arabian nights':[
['Start a Tale','Qualify and start one of the Tales.','Work the lit Tale feature and make its start shot; follow the display’s instructions for that Tale.'],
['Complete a Tale','Finish one Tale mode.','Make the required shots shown by the display until the Tale is marked complete.'],
['Collect a Jewel','Collect a Jewel award.','Complete the appropriate Tale/feature progression and follow the display for the lit Jewel collect shot.'],
['Start Genie multiball','Light the Genie and hit it to start multiball.','When the Genie is lit, hit the Genie toy; its magnet must catch the ball for the feature to register.'],
['Collect a Genie jackpot','During multiball, spin the Lamp to raise the jackpot, then hit the Genie.','The Lamp spins to increase jackpot value; hit the Genie to collect the lit jackpot.'],
['Relight jackpot with an orbit','After collecting a jackpot, shoot the lit orbit to relight it.','The jackpot collection lights one orbit; shoot the indicated orbit to relight jackpot.'],
['Complete the Princess rescue mode','Start the final Princess rescue multiball and win the struggle.','Follow the five lit shots to pull the Princess toward you; keep hitting shots as the Genie pulls back.'],
['Collect an award at the Bazaar','Shoot the Bazaar scoop when an award is available.','Check the display for the current Bazaar award and shoot the scoop to collect it.'],
['Start multiball from the Bazaar','Use the Bazaar scoop if the machine’s compensation setting allows it.','On some settings, the Bazaar scoop can start multiball; otherwise the Genie hit is required. Confirm on the display.'],
['Complete two Tales','Finish two separate Tale modes in one game.','Start a Tale, complete its display-directed shots, then qualify and finish another Tale.']],
'twilight zone':[
['Spell G-U-M-B-A-L-L','Complete the GUMBALL letters.','Work the lit letter features until GUMBALL is complete; the Gumball Machine is central to several awards.'],
['Start Powerball Mania','Load the Powerball into the Gumball Machine when it is the only ball in play.','Build the Powerball Payoff with Greed Targets, then shoot the right orbit to the Gumball diverter while Powerball Mania is lit.'],
['Collect a Powerball Loop','Complete an orbit with the Powerball.','When the Powerball is detected, an orbit awards a Powerball Loop; use the left orbit during Powerball Mania or either orbit during other multiballs.'],
['Raise the Powerball Payoff','Hit Greed Targets while Powerball is the only ball on the playfield.','Each Greed Target hit adds 5M to the payoff; build it before sending the Powerball to the Gumball Machine.'],
['Defeat the Power during Powerball Mania','Shoot the right ramp to the Powerfield and defeat the Power.','During Powerball Mania, the right ramp feeds the Powerfield; use Magna-Flip and hit the Power before the timer expires.'],
['Collect a Mania Jackpot','Defeat the Power during Powerball Mania.','The Mania Jackpot is awarded for defeating the Power; after each jackpot the Powerfield timer becomes shorter.'],
['Complete a piano/door feature','Complete a named Twilight Zone feature shown on the display.','Use the currently lit feature and follow its display prompts; confirm the feature’s completion award.'],
['Collect a lit gumball award','Shoot the Gumball Machine when its award is lit.','The Gumball Machine cycles major features; check the display and target the machine when the intended award is available.'],
['Start a multiball','Qualify and start one of the game’s multiball features.','Follow the lock/feature lamps and make the lit start shot; verify the multiball name on the display.'],
['Collect a Greed award during Powerball play','Hit a flashing Greed Target during Powerball play.','When the Powerball is the only ball in play, Greed Targets raise the payoff; collect the payoff before loading the ball into the Gumball Machine.']],
'white water':[
['Advance the Vacation Planner','Complete one section of the Vacation Planner.','Check the Vacation Planner in the Status Report or at the Whirlpool/No Way Out shots; finish the current section.'],
['Complete the Vacation Planner','Complete all four Vacation Planner sections.','Track all four sections and finish each required feature before collecting the Vacation Jackpot.'],
['Collect the Vacation Jackpot','Complete the Vacation Planner and collect the Vacation Jackpot.','After the four planner sections are complete, use the lit collection shot indicated by the game.'],
['Advance the River','Make shots that advance the river progress.','Follow the river feature lamps and use the lit shots to progress toward the River Master award.'],
['Collect a Whirlpool award','Shoot the Whirlpool when an award is available.','The Whirlpool awards features such as raft progress; check the current award before shooting.'],
['Start Wet Willie’s','Qualify Wet Willie’s and make its start shot.','Use the Whirlpool/raft progression and follow the display for the Wet Willie’s start.'],
['Advance Rafts','Collect raft progress through the Whirlpool feature.','Shoot the Whirlpool when the Advance Raft award is lit and verify the raft inserts advance.'],
['Collect a lit Hazard','Collect a Hazard when it is lit.','Watch the hazard lamps and use the indicated shot to collect a lit hazard; the count contributes to river progress.'],
['Complete a River Master step','Advance the River Master progress.','Use the lit river features and check the display for progress; the River Master challenge requires sustained feature completion.'],
['Collect Vacation Jackpot after all sections','Finish all four Vacation Planner sections, then collect the jackpot.','Do not stop after completing the planner; make the final lit collect shot and confirm the Vacation Jackpot registers.']],
'the addams family':[
['Start Thing multiball','Qualify and start Thing multiball.','Build the lock progress and shoot the Thing/lock feature when lit; confirm multiball starts.'],
['Collect a Bear Kick award','Hit the Bear Kick target when its award is lit.','Check the Bear Kick insert and use the corresponding shot to collect the award.'],
['Complete the mansion rooms','Advance and complete a mansion room feature.','Use the mansion room selection and follow the lit shots for the selected room until it completes.'],
['Collect a Thing award','Shoot Thing when the feature is lit.','Use the Thing feature’s lit shot and verify the display announces the award.'],
['Start Tour the Mansion','Qualify and start Tour the Mansion.','Advance the mansion feature and make the lit start shot when the mode is qualified.'],
['Collect a jackpot during multiball','Start multiball and collect a lit jackpot.','Follow the lit jackpot shot and confirm the display awards it.'],
['Advance the bookcase feature','Progress the bookcase/mansion feature.','Use the shots that advance the bookcase feature and track the display/insert state.'],
['Complete a mansion mode','Finish one selected mansion mode.','Follow the mode’s on-screen shot sequence and wait for the completion indication.'],
['Collect an extra ball','Qualify and collect the lit extra ball.','Follow the game’s extra-ball qualification and shoot the lit collect shot.'],
['Complete two mansion features','Complete two different mansion/Thing features in one game.','Track each feature separately and verify both completion awards register.']],
'the shadow':[
['Light Khan multiball','Complete the lane/target progression that lights Khan multiball.','Follow the Khan feature inserts and complete the required lit lanes before shooting the start shot.'],
['Start Khan multiball','Shoot the lit start shot after qualifying Khan.','Confirm Khan is lit, then make the indicated start shot to begin multiball.'],
['Collect a jackpot','During multiball, hit the lit jackpot shot.','Follow the changing jackpot inserts and confirm the display awards the jackpot.'],
['Complete a city feature','Advance and complete one city-related mode.','Use the lit city feature shots and follow the display until the city mode is complete.'],
['Collect a Shadow award','Shoot the currently lit Shadow feature.','Check the playfield inserts and display for the active Shadow award, then make its shot.'],
['Complete a timed mode','Start and finish a timed Shadow mode.','Read the countdown and lit shots; prioritize the required shots before time expires.'],
['Collect an extra ball','Qualify and collect the extra ball award.','Follow the extra-ball lamps and shoot the lit collect feature before it turns off.'],
['Complete the target sequence','Finish the currently indicated target sequence.','Track the target inserts and hit the missing targets in the displayed order.'],
['Start multiball and collect two jackpots','Start Khan multiball and collect two jackpots.','Qualify and start multiball, then hit two separate lit jackpot shots before the balls drain.'],
['Complete two Shadow features','Finish two distinct named features in one game.','Use the display to verify each feature’s completion; simply starting a mode does not count.']],
'theatre of magic':[
['Spell MAGIC','Complete the MAGIC letters.','Work the lit letter features and track which letters remain until MAGIC is complete.'],
['Start the trunk feature','Qualify and start the trunk feature.','Use the trunk shot when its feature lamp is lit; follow the display for the mode that starts.'],
['Collect a trunk award','Shoot the trunk when a collect award is lit.','Check the trunk insert and make the shot while the intended award is active.'],
['Complete a magic mode','Start and finish one named magic mode.','Follow the display’s required shots and confirm the mode is completed, not merely started.'],
['Start multiball','Qualify and start Theatre of Magic multiball.','Follow the lock/multiball lamps and make the indicated start shot.'],
['Collect a jackpot','During multiball, shoot the lit jackpot feature.','Use the lit jackpot shot and confirm the display awards it.'],
['Complete a mirror feature','Advance and complete the Mirror feature.','Follow the Mirror lamps and display prompts; hit the indicated shots to finish the feature.'],
['Collect a mystery award','Qualify and collect the Mystery award.','Use the shot that lights Mystery and collect it while its insert is active.'],
['Complete MAGIC and trunk','Spell MAGIC and complete one trunk award in one game.','Finish the six-letter word, then use the trunk when its award is lit.'],
['Start and complete a magic mode','Start one mode and finish all required shots.','Read the mode instructions and track the required shots until the display confirms completion.']]
};return p;})());

window.PinheadRulePacks=Object.assign(window.PinheadRulePacks||{},(function(){var p={
'austin powers':[
['Start Time Machine multiball','Qualify and start Time Machine multiball.','Build the Time Machine feature and shoot the lit start/lock shot; confirm multiball begins.'],
['Collect a mojo award','Collect a lit Mojo award.','Work the Mojo feature and check the display for the current award before shooting its collect shot.'],
['Start a Fembot mode','Qualify and start a Fembot feature.','Use the Fembot-related targets/features and follow the display’s start indication.'],
['Complete a mode','Finish one named Austin Powers mode.','Follow the mode’s displayed shots until the game confirms completion.'],
['Collect a Goldmember award','Qualify and collect a Goldmember feature award.','Build the Goldmember feature and shoot the indicated lit shot when ready.'],
['Start multiball','Qualify and start an Austin Powers multiball.','Use the game’s lock/multiball inserts and make the lit start shot.'],
['Collect a jackpot','During multiball, collect a lit jackpot.','Follow the jackpot lamps and confirm the display awards the jackpot.'],
['Advance the Time Machine feature','Make the shots that advance the Time Machine progression.','Track the Time Machine feature lamps/display and complete the next required shot.'],
['Complete two modes','Finish two different named modes in one game.','Choose separate modes and verify each shows completion on the display.'],
['Collect a lit extra ball','Qualify and collect an extra ball award.','Watch for the extra-ball insert and make the indicated collect shot before it turns off.']],
'batman (the dark knight)':[
['Start Joker multiball','Qualify and start Joker multiball.','Build the Joker feature and make the lit lock/start shot shown by the display.'],
['Complete a Scarecrow mode','Start and finish a Scarecrow mode.','Follow the Scarecrow mode’s timed/required shots and wait for the completion indication.'],
['Start Batmobile multiball','Qualify and start Batmobile multiball.','Work the Batmobile feature and follow the lock lamps until the start shot is lit.'],
['Collect a Bat Signal award','Advance the Bat Signal feature and collect its award.','Use the shots indicated by the Bat Signal lamps and confirm the display awards the feature.'],
['Complete a Joker feature','Finish a named Joker feature.','Qualify the Joker feature, then follow its required shots rather than counting a single hit.'],
['Collect a jackpot','During multiball, collect a lit jackpot.','Follow the lit jackpot shots and verify the award registers.'],
['Complete a target-bank sequence','Clear the currently active target bank for mode progress.','Focus on the targets that are lit for the current feature; check the display for progress.'],
['Start a timed villain mode','Start one timed villain mode.','Qualify the mode and make its lit start shot; watch the timer as soon as it begins.'],
['Complete two villain features','Complete two distinct villain-related features in one game.','Track the display’s completion state for each feature; starting alone does not count.'],
['Start multiball and collect a jackpot','Start a multiball and collect one jackpot during it.','Qualify and start multiball, then hit the current jackpot shot before the balls drain.']],
'csi: crime scene investigation':[
['Collect evidence','Complete a shot that awards evidence.','Follow the evidence inserts/display and make the currently indicated evidence shot.'],
['Start a Crime Scene','Qualify and start a Crime Scene mode.','Build the Crime Scene feature and shoot its lit start shot; confirm the case begins.'],
['Complete a Crime Scene','Finish the required shots for one Crime Scene.','Follow the display’s clue/shot sequence until the case is marked complete.'],
['Collect a fingerprint award','Qualify and collect the fingerprint feature award.','Advance the fingerprint feature and use the lit collect shot shown by the display.'],
['Start CSI multiball','Qualify and start CSI multiball.','Follow the lock and multiball inserts, then make the lit start shot.'],
['Collect a jackpot','During multiball, shoot the lit jackpot shot.','Check the current jackpot lamp and confirm the score/award registers.'],
['Complete a case','Finish one full case progression.','Collect the required clues/evidence and finish the case’s final shot shown on the display.'],
['Collect two pieces of evidence','Collect two distinct evidence awards in one game.','Track each evidence award on the display and repeat the qualifying feature for a second one.'],
['Start a mode from the scoop','Shoot the scoop when a mode-start feature is lit.','Confirm the mode is qualified, then shoot the scoop and follow its instructions.'],
['Complete a case and multiball','Finish a case and start multiball in one game.','Complete the evidence/case progression, then qualify and start CSI multiball.']],
'elvis':[
['Start Jailhouse Rock','Qualify and start Jailhouse Rock.','Work the Jailhouse Rock feature and shoot the lit start shot; follow the display once the mode begins.'],
['Complete a song mode','Finish one named Elvis song mode.','Follow the lit shots and display prompts until the song is marked complete.'],
['Collect an Elvis award','Collect a lit Elvis feature award.','Check the current feature insert and shoot its collect location while the award is lit.'],
['Start multiball','Qualify and start an Elvis multiball.','Follow the lock/multiball lamps and make the indicated start shot.'],
['Collect a jackpot','During multiball, collect a lit jackpot.','Follow the jackpot lights and verify the display confirms the award.'],
['Advance the Las Vegas feature','Make the shots that advance Viva Las Vegas/Las Vegas progression.','Watch the Las Vegas feature inserts and make the next lit shot in its sequence.'],
['Complete a song and collect its award','Finish a song mode and collect its completion award.','Complete the display-directed shots, then make the collect shot if the game lights one.'],
['Collect an extra ball','Qualify and collect the lit extra ball.','Use the feature progression that lights extra ball, then shoot the indicated collect shot.'],
['Complete two song modes','Finish two different song modes in one game.','Track which songs are complete and start a different one for the second objective.'],
['Start multiball and collect a jackpot','Start multiball and collect one jackpot in the same game.','Qualify and start multiball, then follow the lit jackpot shot.']],
'family guy':[
['Start Stewie multiball','Qualify and start Stewie multiball.','Work the Stewie feature and use the lit lock/start shot when qualified.'],
['Start Quahog multiball','Qualify and start Quahog multiball.','Follow the Quahog feature lamps and display prompts until the multiball start is lit.'],
['Collect a Cutaway','Start or collect a Cutaway feature.','Use the Cutaway feature shot when its insert is lit and follow the display prompt.'],
['Complete a cutaway mode','Finish one Cutaway mode.','Follow the cutaway’s required shots until the display confirms completion.'],
['Collect a Peter award','Complete a Peter-related feature award.','Use the Peter feature’s lit shot and verify the award registers.'],
['Start multiball','Start any main Family Guy multiball.','Follow the multiball lock/feature lamps and make the lit start shot.'],
['Collect a jackpot','During multiball, collect a lit jackpot.','Track the jackpot shot and confirm the display awards it.'],
['Advance the Quahog feature','Make the shots that advance Quahog progress.','Follow the Quahog inserts and display for the next required shot.'],
['Complete two Cutaways','Complete two separate Cutaway features in one game.','Start and finish each Cutaway, verifying each completion separately.'],
['Start a multiball and a Cutaway','Start multiball and complete a Cutaway in one game.','Qualify and start multiball, then start and finish a Cutaway when the game allows the features to stack.']],
'indiana jones':[
['Collect an artifact','Collect one of the Indiana Jones artifacts.','Complete the feature that awards an artifact and confirm the display announces it.'],
['Start Path of Adventure','Qualify and start Path of Adventure.','Build the Path feature and make the lit start shot; follow the display during the adventure.'],
['Complete a mode','Finish one named Indiana Jones adventure mode.','Follow the displayed shots for the selected adventure until it is marked complete.'],
['Start multiball','Qualify and start Indiana Jones multiball.','Follow the lock and multiball lamps and make the indicated start shot.'],
['Collect a jackpot','During multiball, collect a lit jackpot.','Track the lit jackpot shot and verify the award registers.'],
['Complete a Crystal Skull feature','Advance and complete the Crystal Skull feature.','Work the Crystal Skull shots indicated by the display and confirm the feature completes.'],
['Collect a mode award','Finish a mode and collect its award.','Complete the mode’s required shots, then shoot the collect location if the game lights one.'],
['Complete two adventures','Finish two different Indiana Jones adventure modes in one game.','Track completed adventures and select a different available mode for the second.'],
['Collect two artifacts','Collect two artifacts in one game.','Repeat the feature progression that awards artifacts and confirm both announcements.'],
['Complete Path of Adventure and multiball','Start Path of Adventure and start multiball in one game.','Qualify and start Path of Adventure, then use the lit lock/multiball feature.']],
'lord of the rings':[
['Collect a Ring','Collect a Ring award.','Work the Ring feature and follow the display for the lit collect shot.'],
['Start Fellowship multiball','Qualify and start Fellowship multiball.','Build the Fellowship/lock progress and shoot the lit start shot.'],
['Start Two Towers multiball','Qualify and start Two Towers multiball.','Follow the Two Towers feature lamps and lock progression until multiball begins.'],
['Start Return of the King multiball','Qualify and start Return of the King multiball.','Work the Return of the King progression and make its lit start shot.'],
['Complete a Fellowship mode','Finish one Fellowship-related mode.','Follow the displayed shot sequence until the mode is marked complete.'],
['Complete a Palantir mode','Start and finish a Palantir feature mode.','Use the Palantir feature when lit and follow the display instructions.'],
['Collect a jackpot','During multiball, collect a lit jackpot.','Follow the jackpot lamps and verify the award registers.'],
['Advance the Ring feature','Make shots that advance Ring progress.','Track the Ring inserts/display and complete the next required feature shot.'],
['Complete two movie modes','Finish two different named Lord of the Rings modes.','Start and complete each mode separately; a mode start alone does not count.'],
['Start multiball and collect a jackpot','Start one multiball and collect a jackpot during it.','Qualify multiball, make the start shot, then hit the lit jackpot shot.']],
'monopoly':[
['Collect a property','Collect one property through the board feature.','Advance the Monopoly board and follow the display to collect a property award.'],
['Complete a property set','Collect the properties required for one color group.','Track the color-group progress on the display and collect the missing property.'],
['Collect a Chance award','Qualify and collect a Chance feature award.','Use the Chance feature when lit and follow the display for the resulting award.'],
['Collect Community Chest','Qualify and collect a Community Chest award.','Shoot the Community Chest feature when its insert is lit and confirm the award.'],
['Start Monopoly multiball','Qualify and start Monopoly multiball.','Follow the lock and multiball lamps and make the indicated start shot.'],
['Collect a jackpot','During multiball, collect a lit jackpot.','Follow the current jackpot shot and verify the award registers.'],
['Advance the board','Advance the Monopoly board by one full step/space award.','Use the board-advancing feature and confirm the token/space changes on the display.'],
['Collect a house or hotel award','Advance the property feature until a house/hotel award is collected.','Complete property progress and follow the display for the house/hotel collect shot.'],
['Complete a color set and collect an award','Complete one color group and collect its feature award.','Collect all properties in the group, then make the lit award shot.'],
['Complete two property groups','Complete two distinct property color groups in one game.','Track color-group progress and finish two separate groups on the board display.']],
'nascar':[
['Start Race mode','Qualify and start a Race feature.','Use the race/track progression and shoot the lit start shot shown by the display.'],
['Complete a race','Finish a race mode.','Follow the display’s lap/shot sequence and complete the required race objective.'],
['Collect a Pit Stop award','Qualify and collect the Pit Stop feature.','Shoot the Pit Stop feature when lit and follow the displayed award instructions.'],
['Start multiball','Qualify and start NASCAR multiball.','Follow the lock/multiball inserts and make the lit start shot.'],
['Collect a jackpot','During multiball, collect a lit jackpot.','Follow the current jackpot shot and confirm the award registers.'],
['Advance the race position','Make shots that advance the race position.','Track the race display and hit the next lit shot to pass competitors or advance position.'],
['Collect a Turbo Boost award','Qualify Turbo Boost and collect it.','Use the Turbo Boost feature when its insert is lit and verify the display awards it.'],
['Complete two races','Finish two separate race modes in one game.','Complete one race, then qualify and finish another distinct race.'],
['Complete Pit Stop and race','Collect a Pit Stop award and finish a race in one game.','Use the lit Pit Stop feature, then follow the race mode’s required shots.'],
['Start multiball and collect a jackpot','Start multiball and collect one jackpot during it.','Qualify and start multiball, then shoot the lit jackpot shot.']],
'pirates of the caribbean':[
['Start Cannon multiball','Qualify and start Cannon multiball.','Work the cannon/lock feature and make the lit start shot when qualified.'],
['Collect a cannon jackpot','During multiball, collect a lit cannon jackpot.','Follow the jackpot insert and use the cannon feature when it is lit.'],
['Start a ship battle','Qualify and start a ship battle mode.','Build the ship-battle feature and shoot the lit start shot; follow the display for battle shots.'],
['Complete a ship battle','Finish one ship battle.','Hit the lit battle shots shown by the display until the enemy ship is defeated.'],
['Start Kraken multiball','Qualify and start the Kraken feature/multiball.','Work the Kraken progression and use the lit lock/start shot when it becomes available.'],
['Collect a Kraken award','Hit the Kraken feature when its award is lit.','Check the Kraken insert and make the corresponding shot to collect the award.'],
['Advance the pirate modes','Complete one progression step in a named pirate mode.','Follow the display’s required shots and verify the mode progress advances.'],
['Collect a treasure award','Qualify and collect a treasure feature award.','Work the treasure feature and shoot its lit collect shot when the display indicates it is ready.'],
['Complete two modes','Finish two different Pirates of the Caribbean modes.','Complete each mode’s shot sequence and track the separate completion indications.'],
['Start multiball and win a ship battle','Start multiball and complete a ship battle in one game.','Qualify multiball, then complete the ship-battle shots while the feature remains available.']]
};return p;})());
